### PR TITLE
fix(kafka acl): disallow all alias for principal

### LINKED ISSUE #1330: Handle "all" alias for user and service account flags in kafka acl commands
## Description

**Version**: 0.36.4

Handle "all" alias as flags `--service-account` and `--user` flag for kafka acl commands.

### Steps to reproduce

Add the steps required to reproduce this error.

1. Run command to grant admin access to all service accounts using alias "all" 
> rhoas kafka acl grant-admin --service-account all
2. This should show the preview:
```
PRINCIPAL   PERMISSION   OPERATION   DESCRIPTION                 
 ----------- ------------ ----------- ---------------------------- 
  all         allow        alter       cluster is "kafka-cluster"
```

### Expected behaviour

The alias should be identified and proper error message should be displayed, something like : `To set all principals , pass "--all-accounts".`

### PR DESCRIPTION
**Pull request by rkpattnaik780**
Kafka acl commands should restrict user from setting principal value to `all` along with `*`.

Closes #1330 

### Verification Steps
1. Try to run grant-access with user set to all
> rhoas kafka acl grant-access --producer --user all --topic x 
It should throw the error: `to set a wilcard on the ACL principal, pass "--all-accounts".`

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

### Checklist

- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

File: pkg/cmd/kafka/acl/admin/admin.go [hunk 1]
```diff
@@ -83,7 +83,7 @@ func NewAdminACLCommand(f *factory.Factory) *cobra.Command {
 			}
 
 			// user and service account should not allow wildcard
-			if userID == aclutil.Wildcard || serviceAccount == aclutil.Wildcard {
+			if userID == aclutil.Wildcard || serviceAccount == aclutil.Wildcard || userID == aclutil.AllAlias || serviceAccount == aclutil.AllAlias {
```
Comment (craicoverflow) [inline pkg/cmd/kafka/acl/admin/admin.go:86]: How about `if aclutil.GetResourceName(userID) == aclutil.Wildcard`

**Review by craicoverflow — APPROVED** [review]

File: pkg/cmd/kafka/acl/admin/admin.go (hunk 1 above)
Comment (rkpattnaik780) [reply pkg/cmd/kafka/acl/admin/admin.go:86]: I don't think it will be a good idea to use `GetResourceName` at places that don't support alias.
