### PR TITLE
fix(kafka topic): update regexp for topic name

### LINKED ISSUE #654: Topic names should allow a full-stop (".")
## Description

The topic name validation in the CLI prevents a full-stop from being added to a topic name, but this is wrong and should be allowed.

### PR DESCRIPTION
**Pull request by rkpattnaik780**
Closes #654 

### Verification Steps

1. Run the command to interactively create a kafka topic
```
go run ./cmd/rhoas kafka topic create
```
2. `kafka.k` should be valid and accepted whereas `.` and `..` should be rejected.

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

### Checklist

- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

File: pkg/kafka/topic/validators.go [hunk 1]
```diff
@@ -13,7 +13,7 @@ import (
 )
 
 const (
-	legalNameChars = "^[a-zA-Z0-9\\_\\-]+$"
+	legalNameChars = `[a-zA-Z0-9._-]`
```
Comment (craicoverflow) [inline pkg/kafka/topic/validators.go:16]:
```suggestion
	legalNameChars = "[a-zA-Z0-9._-]"
```

File: pkg/kafka/topic/validators.go [hunk 2]
```diff
@@ -32,13 +32,17 @@ func ValidateName(val interface{}) error {
 		return fmt.Errorf("topic name cannot exceed %v characters", maxNameLength)
 	}
 
+	if (name == ".") || (name == "..") {
+		return fmt.Errorf(`invalid topic name "%v"; can't be "." or ".."`, name)
```
Comment (craicoverflow) [inline pkg/kafka/topic/validators.go:36]: No need to repeat the topic name is we know it is either "." or ".." already.

```suggestion
		return errors.New(`topic name can not be "." or ".."`)
```

**Review by craicoverflow — APPROVED** [review]
A couple of small nits which would make small improvements to UX (mainly the error message) but nothing major. Love the tests!

**Review by craicoverflow — APPROVED** [review]
