### PR TITLE
fix(service-registry create): fetch registry URL after creation

### LINKED ISSUE #1574: Service registry create missing details for connection urls
## Description

Execute:
 rhoas service-registry create --name=test

## Output

```
✔️  Successfully created Service Registry instance
You can connect to the Service Registry instance using following options:
 - For Apicurio Service Registry API:
    /apis/registry/v2
 - For tools supporting Confluent Schema Registry API:  
    /apis/ccompat/v6
 - For CNCF Schema Registry API:
    /apis/cncf/v0

{
  "browserUrl": "https://qaprodauth.cloud.redhat.com/application-services/service-registry/t/52f0461c-6689-489c-aebd-f548f25d5cf9",
  "created_at": "2022-05-17T15:07:33Z",
  "href": "/api/serviceregistry_mgmt/v1/registries/52f0461c-6689-489c-aebd-f548f25d5cf9",
  "id": "52f0461c-6689-489c-aebd-f548f25d5cf9",
  "instance_type": "eval",
  "kind": "ServiceRegistry",
  "name": "test",
  "owner": "wtrocki@redhat.com",
  "status": "accepted",
  "updated_at": "2022-05-17T15:07:33Z"
}
```

Output seems strange. Urls missing the service url when creating registry

### PR DESCRIPTION
**Pull request by rkpattnaik780**
`rhoas service-registry create` now fetches registry URL and shows correct compatibility endpoints.

Closes #1574 

### Verification Steps
1. Run the following command to create a registry:
```
rhoas service-registry create
```
2. You should be able to see the registry URL along with compatibility endpoints once creation is successful.

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

### CODE REVIEW

File: pkg/cmd/registry/create/create.go [hunk 1]
```diff
@@ -156,7 +157,16 @@ func runCreate(opts *options) error {
...
+	registry, _, err := serviceregistryutil.GetServiceRegistryByID(opts.Context, conn.API().ServiceRegistryMgmt(), response.GetId())
+	if err != nil {
+		return err
+	}
+
+	if err = dump.Formatted(opts.IO.Out, opts.outputFormat, registry); err != nil {
+		return err
+	}
+
+	compatibleEndpoints := registrycmdutil.GetCompatibilityEndpoints(registry.GetRegistryUrl())
```
Comment (wtrocki) [inline pkg/cmd/registry/create/create.go:169]: Trick is that this is async call so when I run this pointed to local it can still return nil 

```suggestion
      if registry.GetRegistryUrl() != nil {
	compatibleEndpoints := registrycmdutil.GetCompatibilityEndpoints(registry.GetRegistryUrl())
      } else {
          // To get list of compatible endpoints please run `describe` command
      }
```

File: pkg/core/localize/locales/en/cmd/registry_crud.en.toml [hunk 2]
```diff
@@ -46,6 +46,13 @@ one = 'Successfully created Service Registry instance'
 [registry.cmd.create.info.action]
 one = 'Creating Service Registry instance with name: {{.Name}}'
 
+[registry.cmd.create.info.compatibilityEndpointHint]
+one = '''
+Run the following command to view compatible endpoints:
```
Comment (wtrocki) [inline pkg/core/localize/locales/en/cmd/registry_crud.en.toml:51]:
```suggestion
Run the following command to view service status
```

**Review by wtrocki — APPROVED** [review]

**Comment by wtrocki** [comment]
I have run this with local service registry for testing. I think in more than 70% of cases without huge load users should see endpoints anyway.
