### PR TITLE
fix(kafka update): broken preview

### LINKED ISSUE #1302: Broken update summary for Kafka update operation
## Description

Update summary while doing owner update seems to be broken.

**Version**: 0.36.2

Screenshot from 2021-11-09 13-35-36

### Steps to reproduce

Change owner for a given kafka instance
```
rhoas kafka update --owner=foo_user
```
It should display the update summary.

### PR DESCRIPTION
**Pull request by rkpattnaik780**
Closes #1302, #1224

### Verification Steps
1. Run `rhoas kafka update --owner foo_user`
2. This should display the existing user and the new user to be set

### Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

### Checklist

- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Comment by rkpattnaik780** [comment]
Added a few todos for when cli will work with `ReauthenticationEnabled`. Currently handles only string values, needs modification to support other types later.

File: pkg/cmd/kafka/update/update.go [hunk 1]
```diff
@@ -281,20 +282,23 @@ func promptConfirmUpdate(opts *options) (bool, error) {
 // creates a summary of what values will be changed in this update
 // returns a formatted string. Example:
 // owner: foo_user	➡️	bar_user
+// to do: Needs update once reauthentication_enabled is incorporated
```
Comment (wtrocki) [inline pkg/cmd/kafka/update/update.go:285]: How reauthentication_enabled affects this preview?

Comment (rkpattnaik780) [reply pkg/cmd/kafka/update/update.go:285]: The methods generating preview iterate through the entire update struct, the broken preview did display `reauthentication_enabled` too.

File: pkg/cmd/kafka/update/update.go [hunk 2]
```diff
@@ -281,20 +282,23 @@ func promptConfirmUpdate(opts *options) (bool, error) {
...
 func generateUpdateSummary(new reflect.Value, current reflect.Value) string {
 	var summary string
 
 	newT := new.Type()
 
-	for i := 0; i < new.NumField(); i++ {
+	for i := 0; i < 1; i++ {
```
Comment (craicoverflow) [inline pkg/cmd/kafka/update/update.go:291]: I'm just curious what this does, how it fixes it?

**Review by craicoverflow — DISMISSED** [review]

File: pkg/cmd/kafka/update/update.go (hunk 2 above)
Comment (rkpattnaik780) [reply pkg/cmd/kafka/update/update.go:291]: This is to hide the `reauthentication_nabled` from preview.

[the remark this answers is not in the document]
Comment (wtrocki) [reply pkg/cmd/kafka/update/update.go:291]: It looks like in is not stable/subject to break when api return new data

Comment (craicoverflow) [reply pkg/cmd/kafka/update/update.go:291]: Yes I understand _why_ it was done, I just did not yet understand _how_. I've debugged locally to understand it now.

This is a "quick fix" but once reauth update is possible we won't be able to just revert this change. If the update does not include and change to `reauthentication_enabled`, reverting this will still include it in the update summary.

I see that the value of ReauthenticationEnabled is nil, so perhaps we can check for nil before including it in the update summary?

This also assumes that the owner field will always be the first property of the update object, we should not rely on this.

File: pkg/cmd/kafka/update/update.go (hunk 1 above)
Comment (wtrocki) [reply pkg/cmd/kafka/update/update.go:285]: Yes. That iteration thru all elements of struct is core issue IMHO

Comment (craicoverflow) [reply pkg/cmd/kafka/update/update.go:285]: We need to filter out the nil properties of the update object.

File: pkg/cmd/kafka/update/update.go [hunk 3]
```diff
@@ -308,3 +314,13 @@ func getElementValue(v reflect.Value) reflect.Value {
 	}
 	return v
 }
+
+// get the true value from a reflect.Value for KafkaUpdateRequest struct
+// to do: Needs update once reauthentication_enabled is incorporated
+func getUpdateObjValue(v reflect.Value) reflect.Value {
+	if v.Kind() == reflect.Struct {
+		vstruct := v.Field(0)
```
Comment (rkpattnaik780) [inline pkg/cmd/kafka/update/update.go:322]: A better waywould be to get the `value` field instead of index. Do we need to iterate through this struct as well?

Comment (craicoverflow) [reply pkg/cmd/kafka/update/update.go:322]: This should work:

```suggestion
		vstruct := v.FieldByName("value")
```

This should suffice, no need to iterate.

Though I'm starting to think going forward with reflection on this is a bad idea, as we are making assumptions that are tightly coupled with the SDK, which could introduce breaking changes in the future by changing the name from "value" and since this is not strongly typed, we would not catch it..

For now, once you update with the suggestion above, we can merge as it is blocking any releases. Could you create a follow up issue to address this? We can simplify it by operating directly on the SDK model properties instead.

Comment (rkpattnaik780) [reply pkg/cmd/kafka/update/update.go]: Done!
Ready for review.

**Review by craicoverflow — APPROVED** [review]
