### PR TITLE
fix(serviceaccount reset-credentials): validate serviceaccount ID in prompt

### LINKED ISSUE #716: Add validation for the Service Account ID in interactive mode
```shell
? Service Account ID: https://api.stage.openshift.com/?urls.primaryName=Service%20Registry%20service%20fleet%20manager%20service
? Credentials file format:  [Use arrows to move, type to filter, ? for more help]
> env
  json
  properties
❯ rhoas serviceaccount reset-credentials
```

If I interactively enter the service account ID, it should validate that the ID is a UUID.

### PR DESCRIPTION
**Pull request by rkpattnaik780**
Client side validation for service account ID in interactive mode.

Closes #716

### Verification Steps

1. Run command to reset credentials for service account in interactive mode.
```
go run ./cmd/rhoas serviceaccount reset-credentials
```
2. Input any random string that is not an UUID, e.g `"kafka"`. It should throw the error:
```
Sorry, your reply was invalid: "kafka" is not a valid UUID
```

Screenshot from 2021-06-15 18-53-53

### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change
- [ ] Other (please specify)

### Checklist

- [ ] Documentation added for the feature
- [ ] CI and all relevant tests are passing
- [ ] Code Review completed
- [ ] Verified independently by reviewer

### CODE REVIEW

**Comment by rkpattnaik780** [comment]
Should client side validation be extended to non-interactive mode as well?
```
validateIDFlag := validation.ValidateID(opts.localizer)
validID := validateIDFlag(opts.id)
if validID != nil {
return validID
}
```
Also, it seems bit complex to write tests for higher order functions being used as validators.

File: pkg/serviceaccount/validation/validation.go [hunk 1]
```diff
@@ -63,3 +65,22 @@ func ValidateDescription(val interface{}) error {
 
 	return errors.New(`invalid service account description; only alphanumeric characters and "-", ".", "," are accepted`)
 }
+
+// ValidateID validates if ID is a valid UUID
+func ValidateID(localizer localize.Localizer) func(v interface{}) error {
```
Comment (craicoverflow) [inline pkg/serviceaccount/validation/validation.go:70]:
```suggestion
func ValidateUUID(localizer localize.Localizer) func(v interface{}) error {
```

File: pkg/serviceaccount/validation/validation.go [hunk 2]
```diff
@@ -6,13 +6,15 @@ import (
...
 	"github.com/redhat-developer/app-services-cli/pkg/common/commonerr"
+	"github.com/redhat-developer/app-services-cli/pkg/localize"
 )
 
 const (
 	// name validation rules
 	legalNameChars = "^[a-z]([-a-z0-9]*[a-z0-9])?$"
 	maxNameLength  = 50
 	minNameLength  = 1
+	leagalUUID     = "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
```
Comment (craicoverflow) [inline pkg/serviceaccount/validation/validation.go:17]:
```suggestion
	legalUUID     = "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
```

**Review by craicoverflow — COMMENTED** [review]
> Should client side validation be extended to non-interactive mode as well?

Yes, we should. Any client-side validation improves UX/DX so this would be nice to have.

> Also, it seems bit complex to write tests for higher order functions being used as validators.

Yeah, I see what you mean! Now that we are needing to pass `localizer` to validators they are no longer simple functions.

What would be better (and you can do this in this PR) is to create a `Validator` type which contains all the validator functions for service accounts.

File: pkg/serviceaccount/validation/validation.go [hunk 3]
```diff
@@ -63,3 +65,22 @@ func ValidateDescription(val interface{}) error {
 
 	return errors.New(`invalid service account description; only alphanumeric characters and "-", ".", "," are accepted`)
 }
+
+// ValidateUUID validates if ID is a valid UUID
+func ValidateUUID(localizer localize.Localizer) func(v interface{}) error {
```
Comment (craicoverflow) [inline pkg/serviceaccount/validation/validation.go:70]: I think it will be a good idea for readibility if we do not use anonymous return functions anymore for all validators. I'll explain in a follow up issue

File: pkg/serviceaccount/validation/validation_test.go [hunk 4]
```diff
@@ -69,6 +71,58 @@ func TestValidateName(t *testing.T) {
 	}
 }
 
+func TestValidateUUID(t *testing.T) {
```
Comment (craicoverflow) [inline pkg/serviceaccount/validation/validation_test.go:74]: ❤️

**Review by craicoverflow — APPROVED** [review]

File: pkg/serviceaccount/validation/validation.go (hunk 3 above)
Comment (rkpattnaik780) [reply pkg/serviceaccount/validation/validation.go:70]: > PS: It would also be nice to validate the flag for UUId like you had suggested.

It has been done in `reset_credentials.go`. Did you expect something else?

Comment (rkpattnaik780) [reply pkg/serviceaccount/validation/validation.go:70]: > I think it will be a good idea for readibility if we do not use anonymous return functions anymore for all validators. I'll explain in a follow up issue

Maked #721 as WIP, it has localizations for validators using anonymous functions, should this PR wait for the issue?

Comment (craicoverflow) [reply pkg/serviceaccount/validation/validation.go:70]: No you can merge this PR beforehand if you like.
