### PR TITLE
fix(iostreams): make coloured output work on Windows

### LINKED ISSUE #621: Printing xterm colors in windows cmd
## Description

**Version**:0.23.1 

on windows cmd after successful login rhoas prints url which uses xterm colors but it is not interpreted in windows cmd.

### Expected vs actual behaviour

In windows cmd line

### Logs
```
You are now logged in as "kafka-german-pilsner"

[96mA new version of rhoas is available:[0m [95m0.23.1[0m
[96mhttps://github.com/redhat-developer/app-services-cli/releases/tag/0.23.1[0m
```

### PR DESCRIPTION
**Pull request by craicoverflow**
Fixes #621 

## Verification

Set up this project on a Windows machine, check out and run this PR from Command Prompt

OR

Check these screenshots.

**Powershell**
image

**Cmd**
image

### CODE REVIEW

File: pkg/cmd/kafka/consumergroup/describe/describe.go [hunk 1]
```diff
@@ -204,7 +203,8 @@ func printConsumerGroupDetails(w io.Writer, consumerGroupData strimziadminclient
 	activeMembersCount := cgutil.GetActiveConsumersCount(consumers)
 	partitionsWithLagCount := cgutil.GetPartitionsWithLag(consumers)
 
-	fmt.Fprintln(w, color.Bold(localizer.MustLocalizeFromID("kafka.consumerGroup.describe.output.activeMembers")), activeMembersCount, "\t", color.Bold(localizer.MustLocalizeFromID("kafka.consumerGroup.describe.output.partitionsWithLag")), partitionsWithLagCount)
```
Comment (craicoverflow) [inline pkg/cmd/kafka/consumergroup/describe/describe.go:207]: Removed the bolding of text here because Command Prompt does not support ANSI colors. Powershell does and it worked fine though. Do we need to support both??

Comment (craicoverflow) [reply pkg/cmd/kafka/consumergroup/describe/describe.go:207]: image

Here's how it looks without bold titles. Looks just fine. I originally added bold to differentiate it from the values, but capitalising the title does an equally good job.

**Comment by craicoverflow** [comment]
It's a lot of hassle to verify this, so I've added screenshots to help.

File: pkg/cmd/kafka/consumergroup/describe/describe.go (hunk 1 above)
Comment (pmuir) [reply pkg/cmd/kafka/consumergroup/describe/describe.go:207]: Can you detect somehow?

**Comment by pmuir** [comment]
Do we need this one before Summit?

File: pkg/cmd/kafka/consumergroup/describe/describe.go (hunk 1 above)
Comment (craicoverflow) [reply pkg/cmd/kafka/consumergroup/describe/describe.go:207]: Yes - `if runtime.GOOS != "windows"`.

Comment (pmuir) [reply pkg/cmd/kafka/consumergroup/describe/describe.go:207]: I meant between powershell and cmd...

Comment (craicoverflow) [reply pkg/cmd/kafka/consumergroup/describe/describe.go:207]: Oh sorry, no I did not see a simple way..not using Go libraries anyway.

**Comment by craicoverflow** [comment]
> Do we need this one before Summit?

It depends - the output looks poor and does not give a good impression to Windows users.
It does not block functionality but you get something like this:

```
You are now logged in as "kafka-german-pilsner"

[96mA new version of rhoas is available:[0m [95m0.23.1[0m
[96mhttps://github.com/redhat-developer/app-services-cli/releases/tag/0.23.1[0m
```

File: pkg/cmd/kafka/consumergroup/describe/describe.go (hunk 1 above)
Comment (pmuir) [reply pkg/cmd/kafka/consumergroup/describe/describe.go:207]: That sucks. I guess we need to support both... I'm not sure how well adopted powershell actually is.

**Comment by pmuir** [comment]
Aha -thanks for providing the for - I wasn't sure if it was just to enable colours on Windows!

Yes, then we should do this.

**Review by pmuir — APPROVED** [review]

File: pkg/cmd/kafka/consumergroup/describe/describe.go (hunk 1 above)
Comment (craicoverflow) [reply pkg/cmd/kafka/consumergroup/describe/describe.go:207]: Not sure either, it seems much better and has the same commands as Unix. Best to support both until we know for sure.
