### PR TITLE
fix: fixed the problem with a verbose flag

### LINKED ISSUE #1034: `--verbose/-v` flag is not working in commands with one subcommand
## Description

When you run a command which has a single subcommand, the `verbose` flag is ineffective.

Example: run `rhoas login -v`

### Expected vs actual behaviour

Expected behaviour:

```shell
$ rhoas login -v
Refreshing tokens
...
Logging in...
```

Actual behaviour:

```shell
$ rhoas login -v
Logging in...
```

### PR DESCRIPTION
**Pull request by alexal**
I've added a new SetDebug() function to the Logger interface and implemented it in the StdLoggerBuilder. Also, I've moved debug.Enabled() out of default.go file to the main.go and placed it after the command line arguments definition, so the verbose flag will be properly read and set.

Closes #1034

### CODE REVIEW

**Comment by alexal** [comment]
Now, the debug is working properly
image

File: pkg/cmd/root/root.go [hunk 1]
```diff
@@ -29,6 +30,9 @@ func NewRootCommand(f *factory.Factory, version string) *cobra.Command {
 		Short:         f.Localizer.MustLocalize("root.cmd.shortDescription"),
 		Long:          f.Localizer.MustLocalize("root.cmd.longDescription"),
 		Example:       f.Localizer.MustLocalize("root.cmd.example"),
+		PersistentPreRun: func(cmd *cobra.Command, args []string) {
+			f.Logger.SetDebug(debug.Enabled())
```
Comment (wtrocki) [inline pkg/cmd/root/root.go:34]: That will run for some meta commands like __completion

Comment (wtrocki) [reply pkg/cmd/root/root.go:34]: I would set this as part of the run code

**Review by wtrocki — APPROVED** [review]
Amazing work! Thank you so much

File: pkg/cmd/root/root.go (hunk 1 above)
Comment (alexal) [reply pkg/cmd/root/root.go:34]: > I would set this as part of the run code

Do you recommend any particular place for that? I can check if debug is reported as enabled there.

Comment (wtrocki) [reply pkg/cmd/root/root.go:34]: After line 39 in the same file seems more cleaner

Comment (wtrocki) [reply pkg/cmd/root/root.go:34]: After arguments.AddDebugFlag(fs)

Comment (alexal) [reply pkg/cmd/root/root.go:34]: > After arguments.AddDebugFlag(fs)

Unfortunately debug.Enabled() returns false there...

image

**Comment by wtrocki** [comment]
I have tried to read -v flag in root and avoid running things in the command context but without success. This seems to be the best option
